//
// CEPAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



open class CEPAPI: APIBase {
    /**

     - parameter estado: (path) Abreviaçáo do Estado. 
     - parameter municipio: (query) Nome do Município. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func cepEstadoGet(estado: String, municipio: String? = nil, completion: @escaping ((_ data: [FaixaCEP]?,_ error: Error?) -> Void)) {
        cepEstadoGetWithRequestBuilder(estado: estado, municipio: municipio).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /cep/{estado}
     - Pesquisa pela faixa de CEPs nos municipios de um Estado.
     - examples: [{contentType=application/json, example=[ {
  "inicio" : "13000001",
  "nome" : "Campinas",
  "fim" : "13139999"
} ]}]
     
     - parameter estado: (path) Abreviaçáo do Estado. 
     - parameter municipio: (query) Nome do Município. (optional)

     - returns: RequestBuilder<[FaixaCEP]> 
     */
    open class func cepEstadoGetWithRequestBuilder(estado: String, municipio: String? = nil) -> RequestBuilder<[FaixaCEP]> {
        var path = "/cep/{estado}"
        path = path.replacingOccurrences(of: "{estado}", with: "\(estado)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:Any?] = [
            "municipio": municipio
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[FaixaCEP]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
