//
// Endereco.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Customer Model */
open class Endereco: JSONEncodable {
    /** Nome do logradouro */
    public var logradouro: String?
    /** Nome do Bairro */
    public var bairro: String?
    /** Nome do municipio */
    public var municipio: String?
    /** Estado */
    public var uf: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["logradouro"] = self.logradouro
        nillableDictionary["bairro"] = self.bairro
        nillableDictionary["municipio"] = self.municipio
        nillableDictionary["uf"] = self.uf
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
