//
// Erro.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Erro: JSONEncodable {
    public var resultado: String?
    public var status: String?
    public var detalhes: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["resultado"] = self.resultado
        nillableDictionary["status"] = self.status
        nillableDictionary["detalhes"] = self.detalhes
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
