//
// ObjetoPostal.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Postal Object model */
open class ObjetoPostal: JSONEncodable {
    /** Número do Objeto Postal */
    public var numero: String?
    public var eventos: [Eventos]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["numero"] = self.numero
        nillableDictionary["eventos"] = self.eventos?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
